// Generated by gencpp from file sdpo_ros_interfaces_hw/mot_enc.msg
// DO NOT EDIT!


#ifndef SDPO_ROS_INTERFACES_HW_MESSAGE_MOT_ENC_H
#define SDPO_ROS_INTERFACES_HW_MESSAGE_MOT_ENC_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sdpo_ros_interfaces_hw
{
template <class ContainerAllocator>
struct mot_enc_
{
  typedef mot_enc_<ContainerAllocator> Type;

  mot_enc_()
    : encoder_delta(0)
    , ticks_per_rev(0.0)
    , angular_speed(0.0)  {
    }
  mot_enc_(const ContainerAllocator& _alloc)
    : encoder_delta(0)
    , ticks_per_rev(0.0)
    , angular_speed(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _encoder_delta_type;
  _encoder_delta_type encoder_delta;

   typedef double _ticks_per_rev_type;
  _ticks_per_rev_type ticks_per_rev;

   typedef double _angular_speed_type;
  _angular_speed_type angular_speed;





  typedef boost::shared_ptr< ::sdpo_ros_interfaces_hw::mot_enc_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sdpo_ros_interfaces_hw::mot_enc_<ContainerAllocator> const> ConstPtr;

}; // struct mot_enc_

typedef ::sdpo_ros_interfaces_hw::mot_enc_<std::allocator<void> > mot_enc;

typedef boost::shared_ptr< ::sdpo_ros_interfaces_hw::mot_enc > mot_encPtr;
typedef boost::shared_ptr< ::sdpo_ros_interfaces_hw::mot_enc const> mot_encConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sdpo_ros_interfaces_hw::mot_enc_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sdpo_ros_interfaces_hw::mot_enc_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sdpo_ros_interfaces_hw::mot_enc_<ContainerAllocator1> & lhs, const ::sdpo_ros_interfaces_hw::mot_enc_<ContainerAllocator2> & rhs)
{
  return lhs.encoder_delta == rhs.encoder_delta &&
    lhs.ticks_per_rev == rhs.ticks_per_rev &&
    lhs.angular_speed == rhs.angular_speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sdpo_ros_interfaces_hw::mot_enc_<ContainerAllocator1> & lhs, const ::sdpo_ros_interfaces_hw::mot_enc_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sdpo_ros_interfaces_hw

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sdpo_ros_interfaces_hw::mot_enc_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sdpo_ros_interfaces_hw::mot_enc_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sdpo_ros_interfaces_hw::mot_enc_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sdpo_ros_interfaces_hw::mot_enc_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sdpo_ros_interfaces_hw::mot_enc_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sdpo_ros_interfaces_hw::mot_enc_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sdpo_ros_interfaces_hw::mot_enc_<ContainerAllocator> >
{
  static const char* value()
  {
    return "97ac43cb6fb03e89b82c670503f65f5d";
  }

  static const char* value(const ::sdpo_ros_interfaces_hw::mot_enc_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x97ac43cb6fb03e89ULL;
  static const uint64_t static_value2 = 0xb82c670503f65f5dULL;
};

template<class ContainerAllocator>
struct DataType< ::sdpo_ros_interfaces_hw::mot_enc_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sdpo_ros_interfaces_hw/mot_enc";
  }

  static const char* value(const ::sdpo_ros_interfaces_hw::mot_enc_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sdpo_ros_interfaces_hw::mot_enc_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 encoder_delta\n"
"float64 ticks_per_rev\n"
"float64 angular_speed\n"
;
  }

  static const char* value(const ::sdpo_ros_interfaces_hw::mot_enc_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sdpo_ros_interfaces_hw::mot_enc_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.encoder_delta);
      stream.next(m.ticks_per_rev);
      stream.next(m.angular_speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mot_enc_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sdpo_ros_interfaces_hw::mot_enc_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sdpo_ros_interfaces_hw::mot_enc_<ContainerAllocator>& v)
  {
    s << indent << "encoder_delta: ";
    Printer<int32_t>::stream(s, indent + "  ", v.encoder_delta);
    s << indent << "ticks_per_rev: ";
    Printer<double>::stream(s, indent + "  ", v.ticks_per_rev);
    s << indent << "angular_speed: ";
    Printer<double>::stream(s, indent + "  ", v.angular_speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SDPO_ROS_INTERFACES_HW_MESSAGE_MOT_ENC_H
