// Generated by gencpp from file sdpo_ros_interfaces_hw/mot_ref.msg
// DO NOT EDIT!


#ifndef SDPO_ROS_INTERFACES_HW_MESSAGE_MOT_REF_H
#define SDPO_ROS_INTERFACES_HW_MESSAGE_MOT_REF_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sdpo_ros_interfaces_hw
{
template <class ContainerAllocator>
struct mot_ref_
{
  typedef mot_ref_<ContainerAllocator> Type;

  mot_ref_()
    : angular_speed_ref()  {
    }
  mot_ref_(const ContainerAllocator& _alloc)
    : angular_speed_ref(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _angular_speed_ref_type;
  _angular_speed_ref_type angular_speed_ref;





  typedef boost::shared_ptr< ::sdpo_ros_interfaces_hw::mot_ref_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sdpo_ros_interfaces_hw::mot_ref_<ContainerAllocator> const> ConstPtr;

}; // struct mot_ref_

typedef ::sdpo_ros_interfaces_hw::mot_ref_<std::allocator<void> > mot_ref;

typedef boost::shared_ptr< ::sdpo_ros_interfaces_hw::mot_ref > mot_refPtr;
typedef boost::shared_ptr< ::sdpo_ros_interfaces_hw::mot_ref const> mot_refConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sdpo_ros_interfaces_hw::mot_ref_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sdpo_ros_interfaces_hw::mot_ref_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sdpo_ros_interfaces_hw::mot_ref_<ContainerAllocator1> & lhs, const ::sdpo_ros_interfaces_hw::mot_ref_<ContainerAllocator2> & rhs)
{
  return lhs.angular_speed_ref == rhs.angular_speed_ref;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sdpo_ros_interfaces_hw::mot_ref_<ContainerAllocator1> & lhs, const ::sdpo_ros_interfaces_hw::mot_ref_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sdpo_ros_interfaces_hw

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sdpo_ros_interfaces_hw::mot_ref_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sdpo_ros_interfaces_hw::mot_ref_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sdpo_ros_interfaces_hw::mot_ref_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sdpo_ros_interfaces_hw::mot_ref_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sdpo_ros_interfaces_hw::mot_ref_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sdpo_ros_interfaces_hw::mot_ref_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sdpo_ros_interfaces_hw::mot_ref_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f7b52b672703e430e773f7297473d891";
  }

  static const char* value(const ::sdpo_ros_interfaces_hw::mot_ref_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf7b52b672703e430ULL;
  static const uint64_t static_value2 = 0xe773f7297473d891ULL;
};

template<class ContainerAllocator>
struct DataType< ::sdpo_ros_interfaces_hw::mot_ref_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sdpo_ros_interfaces_hw/mot_ref";
  }

  static const char* value(const ::sdpo_ros_interfaces_hw::mot_ref_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sdpo_ros_interfaces_hw::mot_ref_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] angular_speed_ref\n"
;
  }

  static const char* value(const ::sdpo_ros_interfaces_hw::mot_ref_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sdpo_ros_interfaces_hw::mot_ref_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angular_speed_ref);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mot_ref_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sdpo_ros_interfaces_hw::mot_ref_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sdpo_ros_interfaces_hw::mot_ref_<ContainerAllocator>& v)
  {
    s << indent << "angular_speed_ref[]" << std::endl;
    for (size_t i = 0; i < v.angular_speed_ref.size(); ++i)
    {
      s << indent << "  angular_speed_ref[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.angular_speed_ref[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SDPO_ROS_INTERFACES_HW_MESSAGE_MOT_REF_H
