// Generated by gencpp from file sdpo_ros_interfaces_hw/mot_enc_array.msg
// DO NOT EDIT!


#ifndef SDPO_ROS_INTERFACES_HW_MESSAGE_MOT_ENC_ARRAY_H
#define SDPO_ROS_INTERFACES_HW_MESSAGE_MOT_ENC_ARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sdpo_ros_interfaces_hw/mot_enc.h>

namespace sdpo_ros_interfaces_hw
{
template <class ContainerAllocator>
struct mot_enc_array_
{
  typedef mot_enc_array_<ContainerAllocator> Type;

  mot_enc_array_()
    : stamp()
    , mot_enc_array_data()  {
    }
  mot_enc_array_(const ContainerAllocator& _alloc)
    : stamp()
    , mot_enc_array_data(_alloc)  {
  (void)_alloc;
    }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef std::vector< ::sdpo_ros_interfaces_hw::mot_enc_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::sdpo_ros_interfaces_hw::mot_enc_<ContainerAllocator> >> _mot_enc_array_data_type;
  _mot_enc_array_data_type mot_enc_array_data;





  typedef boost::shared_ptr< ::sdpo_ros_interfaces_hw::mot_enc_array_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sdpo_ros_interfaces_hw::mot_enc_array_<ContainerAllocator> const> ConstPtr;

}; // struct mot_enc_array_

typedef ::sdpo_ros_interfaces_hw::mot_enc_array_<std::allocator<void> > mot_enc_array;

typedef boost::shared_ptr< ::sdpo_ros_interfaces_hw::mot_enc_array > mot_enc_arrayPtr;
typedef boost::shared_ptr< ::sdpo_ros_interfaces_hw::mot_enc_array const> mot_enc_arrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sdpo_ros_interfaces_hw::mot_enc_array_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sdpo_ros_interfaces_hw::mot_enc_array_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sdpo_ros_interfaces_hw::mot_enc_array_<ContainerAllocator1> & lhs, const ::sdpo_ros_interfaces_hw::mot_enc_array_<ContainerAllocator2> & rhs)
{
  return lhs.stamp == rhs.stamp &&
    lhs.mot_enc_array_data == rhs.mot_enc_array_data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sdpo_ros_interfaces_hw::mot_enc_array_<ContainerAllocator1> & lhs, const ::sdpo_ros_interfaces_hw::mot_enc_array_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sdpo_ros_interfaces_hw

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sdpo_ros_interfaces_hw::mot_enc_array_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sdpo_ros_interfaces_hw::mot_enc_array_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sdpo_ros_interfaces_hw::mot_enc_array_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sdpo_ros_interfaces_hw::mot_enc_array_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sdpo_ros_interfaces_hw::mot_enc_array_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sdpo_ros_interfaces_hw::mot_enc_array_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sdpo_ros_interfaces_hw::mot_enc_array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fb57b8488f2393fd342c9aa24f555ed4";
  }

  static const char* value(const ::sdpo_ros_interfaces_hw::mot_enc_array_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfb57b8488f2393fdULL;
  static const uint64_t static_value2 = 0x342c9aa24f555ed4ULL;
};

template<class ContainerAllocator>
struct DataType< ::sdpo_ros_interfaces_hw::mot_enc_array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sdpo_ros_interfaces_hw/mot_enc_array";
  }

  static const char* value(const ::sdpo_ros_interfaces_hw::mot_enc_array_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sdpo_ros_interfaces_hw::mot_enc_array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time stamp\n"
"sdpo_ros_interfaces_hw/mot_enc[] mot_enc_array_data\n"
"\n"
"================================================================================\n"
"MSG: sdpo_ros_interfaces_hw/mot_enc\n"
"int32 encoder_delta\n"
"float64 ticks_per_rev\n"
"float64 angular_speed\n"
;
  }

  static const char* value(const ::sdpo_ros_interfaces_hw::mot_enc_array_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sdpo_ros_interfaces_hw::mot_enc_array_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.mot_enc_array_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mot_enc_array_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sdpo_ros_interfaces_hw::mot_enc_array_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sdpo_ros_interfaces_hw::mot_enc_array_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "mot_enc_array_data[]" << std::endl;
    for (size_t i = 0; i < v.mot_enc_array_data.size(); ++i)
    {
      s << indent << "  mot_enc_array_data[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::sdpo_ros_interfaces_hw::mot_enc_<ContainerAllocator> >::stream(s, indent + "    ", v.mot_enc_array_data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SDPO_ROS_INTERFACES_HW_MESSAGE_MOT_ENC_ARRAY_H
