# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from sdpo_ros_interfaces_hw/mot_data.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class mot_data(genpy.Message):
  _md5sum = "9296bbf0c26da88feecdfff17cec0da1"
  _type = "sdpo_ros_interfaces_hw/mot_data"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 sample_period
int16 pwm
int32 encoder_delta
float64 ticks_per_rev
float64 angular_speed
"""
  __slots__ = ['sample_period','pwm','encoder_delta','ticks_per_rev','angular_speed']
  _slot_types = ['float64','int16','int32','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       sample_period,pwm,encoder_delta,ticks_per_rev,angular_speed

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(mot_data, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.sample_period is None:
        self.sample_period = 0.
      if self.pwm is None:
        self.pwm = 0
      if self.encoder_delta is None:
        self.encoder_delta = 0
      if self.ticks_per_rev is None:
        self.ticks_per_rev = 0.
      if self.angular_speed is None:
        self.angular_speed = 0.
    else:
      self.sample_period = 0.
      self.pwm = 0
      self.encoder_delta = 0
      self.ticks_per_rev = 0.
      self.angular_speed = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_dhi2d().pack(_x.sample_period, _x.pwm, _x.encoder_delta, _x.ticks_per_rev, _x.angular_speed))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 30
      (_x.sample_period, _x.pwm, _x.encoder_delta, _x.ticks_per_rev, _x.angular_speed,) = _get_struct_dhi2d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_dhi2d().pack(_x.sample_period, _x.pwm, _x.encoder_delta, _x.ticks_per_rev, _x.angular_speed))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 30
      (_x.sample_period, _x.pwm, _x.encoder_delta, _x.ticks_per_rev, _x.angular_speed,) = _get_struct_dhi2d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_dhi2d = None
def _get_struct_dhi2d():
    global _struct_dhi2d
    if _struct_dhi2d is None:
        _struct_dhi2d = struct.Struct("<dhi2d")
    return _struct_dhi2d
