# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from sdpo_ros_interfaces_hw/mot_enc_array.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy
import sdpo_ros_interfaces_hw.msg

class mot_enc_array(genpy.Message):
  _md5sum = "fb57b8488f2393fd342c9aa24f555ed4"
  _type = "sdpo_ros_interfaces_hw/mot_enc_array"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """time stamp
sdpo_ros_interfaces_hw/mot_enc[] mot_enc_array_data

================================================================================
MSG: sdpo_ros_interfaces_hw/mot_enc
int32 encoder_delta
float64 ticks_per_rev
float64 angular_speed
"""
  __slots__ = ['stamp','mot_enc_array_data']
  _slot_types = ['time','sdpo_ros_interfaces_hw/mot_enc[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       stamp,mot_enc_array_data

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(mot_enc_array, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.stamp is None:
        self.stamp = genpy.Time()
      if self.mot_enc_array_data is None:
        self.mot_enc_array_data = []
    else:
      self.stamp = genpy.Time()
      self.mot_enc_array_data = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2I().pack(_x.stamp.secs, _x.stamp.nsecs))
      length = len(self.mot_enc_array_data)
      buff.write(_struct_I.pack(length))
      for val1 in self.mot_enc_array_data:
        _x = val1
        buff.write(_get_struct_i2d().pack(_x.encoder_delta, _x.ticks_per_rev, _x.angular_speed))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      if self.mot_enc_array_data is None:
        self.mot_enc_array_data = None
      end = 0
      _x = self
      start = end
      end += 8
      (_x.stamp.secs, _x.stamp.nsecs,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.mot_enc_array_data = []
      for i in range(0, length):
        val1 = sdpo_ros_interfaces_hw.msg.mot_enc()
        _x = val1
        start = end
        end += 20
        (_x.encoder_delta, _x.ticks_per_rev, _x.angular_speed,) = _get_struct_i2d().unpack(str[start:end])
        self.mot_enc_array_data.append(val1)
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2I().pack(_x.stamp.secs, _x.stamp.nsecs))
      length = len(self.mot_enc_array_data)
      buff.write(_struct_I.pack(length))
      for val1 in self.mot_enc_array_data:
        _x = val1
        buff.write(_get_struct_i2d().pack(_x.encoder_delta, _x.ticks_per_rev, _x.angular_speed))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      if self.mot_enc_array_data is None:
        self.mot_enc_array_data = None
      end = 0
      _x = self
      start = end
      end += 8
      (_x.stamp.secs, _x.stamp.nsecs,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.mot_enc_array_data = []
      for i in range(0, length):
        val1 = sdpo_ros_interfaces_hw.msg.mot_enc()
        _x = val1
        start = end
        end += 20
        (_x.encoder_delta, _x.ticks_per_rev, _x.angular_speed,) = _get_struct_i2d().unpack(str[start:end])
        self.mot_enc_array_data.append(val1)
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I = None
def _get_struct_2I():
    global _struct_2I
    if _struct_2I is None:
        _struct_2I = struct.Struct("<2I")
    return _struct_2I
_struct_i2d = None
def _get_struct_i2d():
    global _struct_i2d
    if _struct_i2d is None:
        _struct_i2d = struct.Struct("<i2d")
    return _struct_i2d
