// Generated by gencpp from file sdpo_ratf_ros_driver/SetMotorsPWMRequest.msg
// DO NOT EDIT!


#ifndef SDPO_RATF_ROS_DRIVER_MESSAGE_SETMOTORSPWMREQUEST_H
#define SDPO_RATF_ROS_DRIVER_MESSAGE_SETMOTORSPWMREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sdpo_ratf_ros_driver
{
template <class ContainerAllocator>
struct SetMotorsPWMRequest_
{
  typedef SetMotorsPWMRequest_<ContainerAllocator> Type;

  SetMotorsPWMRequest_()
    : motors_pwm()  {
    }
  SetMotorsPWMRequest_(const ContainerAllocator& _alloc)
    : motors_pwm(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int16_t>> _motors_pwm_type;
  _motors_pwm_type motors_pwm;





  typedef boost::shared_ptr< ::sdpo_ratf_ros_driver::SetMotorsPWMRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sdpo_ratf_ros_driver::SetMotorsPWMRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetMotorsPWMRequest_

typedef ::sdpo_ratf_ros_driver::SetMotorsPWMRequest_<std::allocator<void> > SetMotorsPWMRequest;

typedef boost::shared_ptr< ::sdpo_ratf_ros_driver::SetMotorsPWMRequest > SetMotorsPWMRequestPtr;
typedef boost::shared_ptr< ::sdpo_ratf_ros_driver::SetMotorsPWMRequest const> SetMotorsPWMRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sdpo_ratf_ros_driver::SetMotorsPWMRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sdpo_ratf_ros_driver::SetMotorsPWMRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sdpo_ratf_ros_driver::SetMotorsPWMRequest_<ContainerAllocator1> & lhs, const ::sdpo_ratf_ros_driver::SetMotorsPWMRequest_<ContainerAllocator2> & rhs)
{
  return lhs.motors_pwm == rhs.motors_pwm;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sdpo_ratf_ros_driver::SetMotorsPWMRequest_<ContainerAllocator1> & lhs, const ::sdpo_ratf_ros_driver::SetMotorsPWMRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sdpo_ratf_ros_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sdpo_ratf_ros_driver::SetMotorsPWMRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sdpo_ratf_ros_driver::SetMotorsPWMRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sdpo_ratf_ros_driver::SetMotorsPWMRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sdpo_ratf_ros_driver::SetMotorsPWMRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sdpo_ratf_ros_driver::SetMotorsPWMRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sdpo_ratf_ros_driver::SetMotorsPWMRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sdpo_ratf_ros_driver::SetMotorsPWMRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8d849fa8efc3b3d6d4674548331cb1a6";
  }

  static const char* value(const ::sdpo_ratf_ros_driver::SetMotorsPWMRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8d849fa8efc3b3d6ULL;
  static const uint64_t static_value2 = 0xd4674548331cb1a6ULL;
};

template<class ContainerAllocator>
struct DataType< ::sdpo_ratf_ros_driver::SetMotorsPWMRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sdpo_ratf_ros_driver/SetMotorsPWMRequest";
  }

  static const char* value(const ::sdpo_ratf_ros_driver::SetMotorsPWMRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sdpo_ratf_ros_driver::SetMotorsPWMRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16[] motors_pwm\n"
;
  }

  static const char* value(const ::sdpo_ratf_ros_driver::SetMotorsPWMRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sdpo_ratf_ros_driver::SetMotorsPWMRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.motors_pwm);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetMotorsPWMRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sdpo_ratf_ros_driver::SetMotorsPWMRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sdpo_ratf_ros_driver::SetMotorsPWMRequest_<ContainerAllocator>& v)
  {
    s << indent << "motors_pwm[]" << std::endl;
    for (size_t i = 0; i < v.motors_pwm.size(); ++i)
    {
      s << indent << "  motors_pwm[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.motors_pwm[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SDPO_RATF_ROS_DRIVER_MESSAGE_SETMOTORSPWMREQUEST_H
