// Generated by gencpp from file sdpo_ratf_ros_driver/SetMotorsPWMResponse.msg
// DO NOT EDIT!


#ifndef SDPO_RATF_ROS_DRIVER_MESSAGE_SETMOTORSPWMRESPONSE_H
#define SDPO_RATF_ROS_DRIVER_MESSAGE_SETMOTORSPWMRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sdpo_ratf_ros_driver
{
template <class ContainerAllocator>
struct SetMotorsPWMResponse_
{
  typedef SetMotorsPWMResponse_<ContainerAllocator> Type;

  SetMotorsPWMResponse_()
    {
    }
  SetMotorsPWMResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::sdpo_ratf_ros_driver::SetMotorsPWMResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sdpo_ratf_ros_driver::SetMotorsPWMResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetMotorsPWMResponse_

typedef ::sdpo_ratf_ros_driver::SetMotorsPWMResponse_<std::allocator<void> > SetMotorsPWMResponse;

typedef boost::shared_ptr< ::sdpo_ratf_ros_driver::SetMotorsPWMResponse > SetMotorsPWMResponsePtr;
typedef boost::shared_ptr< ::sdpo_ratf_ros_driver::SetMotorsPWMResponse const> SetMotorsPWMResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sdpo_ratf_ros_driver::SetMotorsPWMResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sdpo_ratf_ros_driver::SetMotorsPWMResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace sdpo_ratf_ros_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sdpo_ratf_ros_driver::SetMotorsPWMResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sdpo_ratf_ros_driver::SetMotorsPWMResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sdpo_ratf_ros_driver::SetMotorsPWMResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sdpo_ratf_ros_driver::SetMotorsPWMResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sdpo_ratf_ros_driver::SetMotorsPWMResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sdpo_ratf_ros_driver::SetMotorsPWMResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sdpo_ratf_ros_driver::SetMotorsPWMResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::sdpo_ratf_ros_driver::SetMotorsPWMResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::sdpo_ratf_ros_driver::SetMotorsPWMResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sdpo_ratf_ros_driver/SetMotorsPWMResponse";
  }

  static const char* value(const ::sdpo_ratf_ros_driver::SetMotorsPWMResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sdpo_ratf_ros_driver::SetMotorsPWMResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::sdpo_ratf_ros_driver::SetMotorsPWMResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sdpo_ratf_ros_driver::SetMotorsPWMResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetMotorsPWMResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sdpo_ratf_ros_driver::SetMotorsPWMResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::sdpo_ratf_ros_driver::SetMotorsPWMResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // SDPO_RATF_ROS_DRIVER_MESSAGE_SETMOTORSPWMRESPONSE_H
