// Generated by gencpp from file sdpo_ratf_ros_driver/SetMotorsPWM.msg
// DO NOT EDIT!


#ifndef SDPO_RATF_ROS_DRIVER_MESSAGE_SETMOTORSPWM_H
#define SDPO_RATF_ROS_DRIVER_MESSAGE_SETMOTORSPWM_H

#include <ros/service_traits.h>


#include <sdpo_ratf_ros_driver/SetMotorsPWMRequest.h>
#include <sdpo_ratf_ros_driver/SetMotorsPWMResponse.h>


namespace sdpo_ratf_ros_driver
{

struct SetMotorsPWM
{

typedef SetMotorsPWMRequest Request;
typedef SetMotorsPWMResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetMotorsPWM
} // namespace sdpo_ratf_ros_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sdpo_ratf_ros_driver::SetMotorsPWM > {
  static const char* value()
  {
    return "8d849fa8efc3b3d6d4674548331cb1a6";
  }

  static const char* value(const ::sdpo_ratf_ros_driver::SetMotorsPWM&) { return value(); }
};

template<>
struct DataType< ::sdpo_ratf_ros_driver::SetMotorsPWM > {
  static const char* value()
  {
    return "sdpo_ratf_ros_driver/SetMotorsPWM";
  }

  static const char* value(const ::sdpo_ratf_ros_driver::SetMotorsPWM&) { return value(); }
};


// service_traits::MD5Sum< ::sdpo_ratf_ros_driver::SetMotorsPWMRequest> should match
// service_traits::MD5Sum< ::sdpo_ratf_ros_driver::SetMotorsPWM >
template<>
struct MD5Sum< ::sdpo_ratf_ros_driver::SetMotorsPWMRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sdpo_ratf_ros_driver::SetMotorsPWM >::value();
  }
  static const char* value(const ::sdpo_ratf_ros_driver::SetMotorsPWMRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sdpo_ratf_ros_driver::SetMotorsPWMRequest> should match
// service_traits::DataType< ::sdpo_ratf_ros_driver::SetMotorsPWM >
template<>
struct DataType< ::sdpo_ratf_ros_driver::SetMotorsPWMRequest>
{
  static const char* value()
  {
    return DataType< ::sdpo_ratf_ros_driver::SetMotorsPWM >::value();
  }
  static const char* value(const ::sdpo_ratf_ros_driver::SetMotorsPWMRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sdpo_ratf_ros_driver::SetMotorsPWMResponse> should match
// service_traits::MD5Sum< ::sdpo_ratf_ros_driver::SetMotorsPWM >
template<>
struct MD5Sum< ::sdpo_ratf_ros_driver::SetMotorsPWMResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sdpo_ratf_ros_driver::SetMotorsPWM >::value();
  }
  static const char* value(const ::sdpo_ratf_ros_driver::SetMotorsPWMResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sdpo_ratf_ros_driver::SetMotorsPWMResponse> should match
// service_traits::DataType< ::sdpo_ratf_ros_driver::SetMotorsPWM >
template<>
struct DataType< ::sdpo_ratf_ros_driver::SetMotorsPWMResponse>
{
  static const char* value()
  {
    return DataType< ::sdpo_ratf_ros_driver::SetMotorsPWM >::value();
  }
  static const char* value(const ::sdpo_ratf_ros_driver::SetMotorsPWMResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SDPO_RATF_ROS_DRIVER_MESSAGE_SETMOTORSPWM_H
