; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; --- Librerie Dipendenti ---
lib_deps =
    adafruit/Adafruit ADS1X15 @ ^2.5.0    ; Per il tachimetro/ADC se usato
    adafruit/Adafruit BusIO @ ^1.14.1     ; Dipendenza per sensori I2C
    bblanchon/ArduinoJson @ ^6.21.3       ; Per messaggi ROS2/Serial complessi
    lib/
    ;https://github.com/PaulStoffregen/TimerOne.git
    ;https://github.com/PaulStoffregen/TimerThree.git
    ; Se usi librerie custom locali (come 'channels'), assicurati che siano nella cartella /lib

; --- Build Flags ---
build_flags = 
    -D CORE_DEBUG_LEVEL=3                 ; Abilita log di errore sulla seriale
    -D _USE_MATH_DEFINES                  ; Risolve i problemi con M_PI e funzioni matematiche
